// <auto-generated />
using System;
using BookStore.Models.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BookStore.Models.Domain.Author", b =>
                {
                    b.Property<int>("id_author")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_author"), 1L, 1);

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_author");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("BookStore.Models.Domain.Book", b =>
                {
                    b.Property<int>("id_book")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_book"), 1L, 1);

                    b.Property<int>("id_author")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description_book")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_genre")
                        .HasColumnType("int");

                    b.Property<int>("published_year")
                        .HasColumnType("int");

                    b.HasKey("id_book");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookStore.Models.Domain.Genre", b =>
                {
                    b.Property<int>("id_genre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_genre"), 1L, 1);

                    b.Property<string>("name_genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_genre");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("BookStore.Models.Domain.Loan", b =>
                {
                    b.Property<int>("id_loan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_loan"), 1L, 1);

                    b.Property<int>("id_book")
                        .HasColumnType("int");

                    b.Property<DateTime>("loan_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_reader")
                        .HasColumnType("int");

                    b.Property<DateTime>("return_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id_loan");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("BookStore.Models.Domain.Reader", b =>
                {
                    b.Property<int>("id_reader")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_reader"), 1L, 1);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_reader");

                    b.ToTable("Readers");
                });
#pragma warning restore 612, 618
        }
    }
}
